//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwriteTestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentTopicRange
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssessmentTopicRange()
        {
            this.TaskTopicRanges = new HashSet<TaskTopicRange>();
        }
    
        public int idAssessmentTopicRange { get; set; }
        public string CUShort { get; set; }
        public string LOShort { get; set; }
        public string TopicShort { get; set; }
        public int Assessment_idAssessment { get; set; }
        public int LOTopic_idLOTopic { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual LOTopic LOTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTopicRange> TaskTopicRanges { get; set; }
    }
}
