//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwriteTestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assessment()
        {
            this.AssessmentTasks = new HashSet<AssessmentTask>();
            this.UnitsAssesseds = new HashSet<UnitsAssessed>();
            this.AssessmentTopicRanges = new HashSet<AssessmentTopicRange>();
        }
    
        public int idAssessment { get; set; }
        public int AssessmentType_idAssessmentType { get; set; }
        public string AssessmentName { get; set; }
        public string AssessmentCode { get; set; }
        public string Assessment_AssessmentScenario { get; set; }
        public Nullable<int> SystemUser_idSystemUser { get; set; }
        public Nullable<int> Course_idCourse { get; set; }
    
        public virtual AssessmentType AssessmentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTask> AssessmentTasks { get; set; }
        public virtual Course Course { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitsAssessed> UnitsAssesseds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTopicRange> AssessmentTopicRanges { get; set; }
    }
}
