//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwriteTestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseUnit()
        {
            this.UnitsAssesseds = new HashSet<UnitsAssessed>();
        }
    
        public int idCourseUnit { get; set; }
        public int UnitStatus_idUnitStatus { get; set; }
        public int Course_idCourse { get; set; }
        public int QualUnit_idQualUnit { get; set; }
        public string CourseUnitTitle { get; set; }
        public string CUShort { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual QualUnit QualUnit { get; set; }
        public virtual UnitStatu UnitStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitsAssessed> UnitsAssesseds { get; set; }
    }
}
