//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwriteTestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskAO
    {
        public int idTaskAO { get; set; }
        public int AssessmentTask_idAssessmentTask { get; set; }
        public int AssessmentObjective_idAssessmentObjective { get; set; }
    
        public virtual AssessmentObjective AssessmentObjective { get; set; }
        public virtual AssessmentTask AssessmentTask { get; set; }
    }
}
