//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwriteTestBed
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitLearningOutcome
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnitLearningOutcome()
        {
            this.LOTopics = new HashSet<LOTopic>();
        }
    
        public int idUnitLearningOutcome { get; set; }
        public int QualUnit_idQualUnit { get; set; }
        public string LearningOutsomeName { get; set; }
        public int LearningOutcomeNumber { get; set; }
        public string LOShort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTopic> LOTopics { get; set; }
        public virtual QualUnit QualUnit { get; set; }
    }
}
