//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTopic()
        {
            this.AssessmentTopicRanges = new HashSet<AssessmentTopicRange>();
            this.TopicKeywords = new HashSet<TopicKeyword>();
        }
    
        public int idLOTopic { get; set; }
        public int UnitLearningOutcome_idUnitLearningOutcome { get; set; }
        public string TopicName { get; set; }
        public string TopicCode { get; set; }
        public Nullable<int> TopicTestingMethod_idTopicTestingMethod { get; set; }
        public string TopicShort { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentTopicRange> AssessmentTopicRanges { get; set; }
        public virtual TopicTestingMethod TopicTestingMethod { get; set; }
        public virtual UnitLearningOutcome UnitLearningOutcome { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicKeyword> TopicKeywords { get; set; }
    }
}
