//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QualUnit()
        {
            this.CourseUnits = new HashSet<CourseUnit>();
            this.UnitLearningOutcomes = new HashSet<UnitLearningOutcome>();
        }
    
        public int idQualUnit { get; set; }
        public int Qualification_idQualification { get; set; }
        public string QualUnitTitle { get; set; }
        public int CGUnitNumber { get; set; }
        public string QualUnitUAN { get; set; }
        public Nullable<int> QualUnitGLH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseUnit> CourseUnits { get; set; }
        public virtual Qualification Qualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitLearningOutcome> UnitLearningOutcomes { get; set; }
    }
}
