//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qualification()
        {
            this.QualificationPathways = new HashSet<QualificationPathway>();
            this.QualUnits = new HashSet<QualUnit>();
        }
    
        public int idQualification { get; set; }
        public int Curriculum_idCurriculum { get; set; }
        public string QualificationName { get; set; }
        public string QualificationCode { get; set; }
        public Nullable<System.DateTime> QualValidFrom { get; set; }
        public Nullable<System.DateTime> QualValidTo { get; set; }
        public string QualAccreditCode { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualificationPathway> QualificationPathways { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualUnit> QualUnits { get; set; }
    }
}
