//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicKeyword
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopicKeyword()
        {
            this.TaskKeywords = new HashSet<TaskKeyword>();
        }
    
        public int idTopicKeyword { get; set; }
        public int LOTopic_idLOTopic { get; set; }
        public string KeywordText { get; set; }
    
        public virtual LOTopic LOTopic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskKeyword> TaskKeywords { get; set; }
    }
}
