//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AWEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsAssessed
    {
        public int idUnitsAssessed { get; set; }
        public int CourseUnit_idCourseUnit { get; set; }
        public int Assessment_idAssessment { get; set; }
    
        public virtual Assessment Assessment { get; set; }
        public virtual CourseUnit CourseUnit { get; set; }
    }
}
